services:
  corebox:
    container_name: corebox
    image: cto4/devbox:core
    ports:
      - 3001:3000
    volumes:
      - /path/to/project:/workspace
  nodebox:
    container_name: nodebox
    image: cto4/devbox:node
    ports:
      - 3002:3000
    volumes:
      - /path/to/project:/workspace
      - /path/to/.pnpm-store:/root/.local/share/pnpm/store
  phpbox:
    container_name: phpbox
    image: cto4/devbox:php
    ports:
      - 3003:3000
    volumes:
      - /path/to/project:/workspace
  gobox:
    container_name: gobox
    image: cto4/devbox:go
    ports:
      - 3004:3000
    volumes:
      - /path/to/project:/workspace